# Generated by Django 5.2.11 on 2026-02-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'category'], name='directory_l_city_48b5cd_idx')],
            },
        ),
    ]
