# Generated by Django 5.2.11 on 2026-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_listing_address_listing_phone_listing_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
