# Generated by Django 5.2.11 on 2026-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_listing_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
