# Generated by Django 5.2.11 on 2026-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_listing_photo_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
