# Generated by Django 5.2.11 on 2026-02-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_listing_place_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="listing",
            name="directory_l_city_48b5cd_idx",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["city"], name="directory_l_city_b70624_idx"),
        ),
    ]
