# Generated by Django 5.2.11 on 2026-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_remove_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaunaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('county', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Tell us about this sauna')),
                ('heat_source', models.CharField(blank=True, max_length=50)),
                ('cold_plunge', models.CharField(blank=True, max_length=20)),
                ('dog_friendly', models.CharField(blank=True, max_length=20)),
                ('showers', models.CharField(blank=True, max_length=20)),
                ('changing_facilities', models.CharField(blank=True, max_length=20)),
                ('sea_view', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.TextField(blank=True, help_text='Optional: Opening hours information')),
                ('submitter_name', models.CharField(blank=True, max_length=255)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
