# Generated by Django 5.2.11 on 2026-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0008_listing_latitude_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
