# Generated by Django 5.2.11 on 2026-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0009_listing_is_featured"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="listing",
            name="directory_l_city_b70624_idx",
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["county"], name="directory_l_county_2f81bc_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-is_featured", "name"], name="directory_l_is_feat_7f0f17_idx"
            ),
        ),
    ]
