# Generated by Django 5.2.11 on 2026-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0010_remove_listing_directory_l_city_b70624_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="photo_data",
            field=models.TextField(
                blank=True, help_text="Base64 encoded WebP image data"
            ),
        ),
    ]
